#/vis/open DAWNFILE
/vis/open OGL 900x900-0+0
/vis/viewer/set/background white
/vis/viewer/set/style wireframe
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/zoom 100 
/vis/drawVolume

/vis/scene/add/axes 0 0 0 0.5 cm
/tracking/storeTrajectory 2 
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

/vis/viewer/refresh
/vis/drawVolume
/gps/particle e+
/gps/ene/mono 500 MeV
/gps/direction 0 0 -1
/gps/position 0 0 5

/run/initialize
/run/beamOn 1

